version: '3.8'

services:
  popcornhub-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - popcornhub-backend
    networks:
      - popcornhub-network

  popcornhub-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
    networks:
      - popcornhub-network

networks:
  popcornhub-network:
    driver: bridge