version: '3.8'

services:
  popcornhub-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - popcornhub-network

networks:
  popcornhub-network:
    driver: bridge