from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from popcornhub_api.models.base_model import Model
from popcornhub_api import util


class WatchlistPost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """WatchlistPost200Response - a model defined in OpenAPI

        :param message: The message of this WatchlistPost200Response.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'message': str
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'WatchlistPost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _watchlist_post_200_response of this WatchlistPost200Response.  # noqa: E501
        :rtype: WatchlistPost200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this WatchlistPost200Response.


        :return: The message of this WatchlistPost200Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this WatchlistPost200Response.


        :param message: The message of this WatchlistPost200Response.
        :type message: str
        """

        self._message = message
